### PR TITLE
Stabilize benchmark results

### PR DESCRIPTION
**Pull request by sindoudou**
- Update JMH version.
- Use same input in benchmark.

### CODE REVIEW

**Comment by sindoudou** [comment]
I have only tried it with 3 iterations, might be worth to try with more iterations...
The results seems better than before, there is still some difference, but it might be because of the low number of iterations...
I also found that some people use -XX:-BackgroundCompilation, to stop the background compilation during the benchmark...might be something we can investigate if not happy with the current result...

**Comment by julien-truffaut** [comment]
Awesome, thank you @sindoudou. I will give it a try with more iterations

**Comment by julien-truffaut** [comment]
@sindoudou I am getting the following error:

```
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
```

by any chance, did you have the same issue?

**Comment by sindoudou** [comment]
@julien-truffaut, Which command line did you use? I haven't seen that error, here is how I execute it:
`sbt clean compile`
`sbt "bench/jmh:run -i 3 -wi 3 -f1 -t1 -rf=csv .*Lens.*"`

**Comment by julien-truffaut** [comment]
my bad, I forgot to add `jmh:` after `bench/`, I need to document this!
Thanks

**Comment by sindoudou** [comment]
Oh ok! Let me know how it goes :)

**Pull request merged**
